// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBSORefJiUTpNTpVKtfqwvPsnLaQ3DMDA',
    appId: '1:586630346027:android:b81b5d76bf5a730be5816e',
    messagingSenderId: '586630346027',
    projectId: 'whats-for-dinner-606',
    storageBucket: 'whats-for-dinner-606.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUPZ7h4GDd16p0NPkXyw7FNKq0l6buEEE',
    appId: '1:586630346027:ios:ea505d0dc1715dede5816e',
    messagingSenderId: '586630346027',
    projectId: 'whats-for-dinner-606',
    storageBucket: 'whats-for-dinner-606.appspot.com',
    iosClientId: '586630346027-cldksb984itcgadle0q4f6a9qk5k3rvt.apps.googleusercontent.com',
    iosBundleId: 'com.malgorzatamyslicka.whatsForDinner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUPZ7h4GDd16p0NPkXyw7FNKq0l6buEEE',
    appId: '1:586630346027:ios:ea505d0dc1715dede5816e',
    messagingSenderId: '586630346027',
    projectId: 'whats-for-dinner-606',
    storageBucket: 'whats-for-dinner-606.appspot.com',
    iosClientId: '586630346027-cldksb984itcgadle0q4f6a9qk5k3rvt.apps.googleusercontent.com',
    iosBundleId: 'com.malgorzatamyslicka.whatsForDinner',
  );
}
